// i18n catalogue for `mcp-vertex_metrics`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const mcpVertexMetricsI18n: IToolI18n = {
	description: {
		en: 'Return per-tool metrics collected this process: calls, errors, total/max latency (ms) and response bytes, plus totals. Read-only; pass reset:true to zero the counters after reading, or persist:true to dump a timestamped snapshot under <cacheDir>/metrics/ for longitudinal comparison. Quantifies tool cost (e.g. token savings of compact responses).',
		es: 'Devuelve las métricas por herramienta recogidas en este proceso: llamadas, errores, latencia total/máxima (ms) y bytes de respuesta, más los totales. Solo lectura; pasa reset:true para poner a cero los contadores tras leer, o persist:true para volcar una instantánea con marca de tiempo bajo <cacheDir>/metrics/ para comparación longitudinal. Cuantifica el coste de la herramienta (p. ej. el ahorro de tokens de respuestas compactas).',
		fr: "Renvoie les métriques par outil collectées dans ce processus : appels, erreurs, latence totale/maximale (ms) et octets de réponse, plus les totaux. Lecture seule ; passez reset:true pour remettre les compteurs à zéro après lecture, ou persist:true pour vider un instantané horodaté sous <cacheDir>/metrics/ pour une comparaison longitudinale. Quantifie le coût de l'outil (par ex. l'économie de tokens des réponses compactes).",
		de: 'Gibt die in diesem Prozess gesammelten Metriken pro Werkzeug zurück: Aufrufe, Fehler, Gesamt-/Maximallatenz (ms) und Antwort-Bytes, plus Summen. Nur lesend; übergib reset:true, um die Zähler nach dem Lesen auf null zu setzen, oder persist:true, um einen zeitgestempelten Snapshot unter <cacheDir>/metrics/ für den Längsschnittvergleich abzulegen. Quantifiziert die Werkzeugkosten (z. B. Token-Einsparungen kompakter Antworten).',
		it: 'Restituisce le metriche per strumento raccolte in questo processo: chiamate, errori, latenza totale/massima (ms) e byte di risposta, più i totali. Solo lettura; passa reset:true per azzerare i contatori dopo la lettura, o persist:true per salvare uno snapshot con timestamp sotto <cacheDir>/metrics/ per il confronto longitudinale. Quantifica il costo dello strumento (es. risparmio di token delle risposte compatte).',
		pt: 'Devolve as métricas por ferramenta recolhidas neste processo: chamadas, erros, latência total/máxima (ms) e bytes de resposta, mais os totais. Apenas leitura; passa reset:true para zerar os contadores após a leitura, ou persist:true para gravar um snapshot com timestamp em <cacheDir>/metrics/ para comparação longitudinal. Quantifica o custo da ferramenta (ex. poupança de tokens de respostas compactas).',
		ja: 'このプロセスで収集されたツールごとのメトリクスを返します:呼び出し数、エラー数、合計/最大レイテンシ(ms)、レスポンスバイト数、および合計値。読み取り専用;reset:true を渡すと読み取り後にカウンタをゼロにし、persist:true を渡すと縦断的比較用にタイムスタンプ付きスナップショットを <cacheDir>/metrics/ に保存します。ツールのコスト(例:コンパクトなレスポンスによるトークン削減)を定量化します。',
		zh: '返回此进程中收集的各工具指标:调用次数、错误数、总/最大延迟(毫秒)和响应字节数,以及总计。只读;传入 reset:true 可在读取后将计数器清零,或传入 persist:true 可将带时间戳的快照转储到 <cacheDir>/metrics/ 下用于纵向比较。用于量化工具成本(例如紧凑响应节省的令牌数)。',
		hi: 'इस प्रोसेस में एकत्रित प्रति-टूल मेट्रिक्स लौटाता है: कॉल्स, त्रुटियाँ, कुल/अधिकतम विलंबता (ms) और रेस्पॉन्स बाइट्स, साथ ही कुल योग। केवल पढ़ने के लिए; पढ़ने के बाद काउंटर शून्य करने के लिए reset:true पास करें, या अनुदैर्ध्य तुलना के लिए <cacheDir>/metrics/ के अंतर्गत टाइमस्टैम्प वाला स्नैपशॉट डंप करने के लिए persist:true पास करें। टूल की लागत को परिमाणित करता है (जैसे, कॉम्पैक्ट रेस्पॉन्स की टोकन बचत)।',
		ar: 'يُرجع المقاييس لكل أداة التي تم جمعها في هذه العملية: الاستدعاءات، الأخطاء، الكمون الإجمالي/الأقصى (مللي ثانية) وبايتات الاستجابة، بالإضافة إلى الإجماليات. للقراءة فقط؛ مرّر reset:true لتصفير العدادات بعد القراءة، أو persist:true لتفريغ لقطة مختومة بالوقت تحت <cacheDir>/metrics/ للمقارنة الطولية. يقيس تكلفة الأداة (مثل توفير الرموز في الاستجابات المضغوطة).',
		th: 'ส่งคืนเมตริกต่อเครื่องมือที่เก็บรวบรวมในโปรเซสนี้: การเรียก ข้อผิดพลาด เวลาแฝงรวม/สูงสุด (มิลลิวินาที) และไบต์การตอบสนอง รวมถึงยอดรวม อ่านอย่างเดียว ส่ง reset:true เพื่อรีเซ็ตตัวนับเป็นศูนย์หลังอ่าน หรือ persist:true เพื่อบันทึกสแนปช็อตประทับเวลาไว้ใต้ <cacheDir>/metrics/ สำหรับการเปรียบเทียบระยะยาว ใช้วัดต้นทุนของเครื่องมือ (เช่น การประหยัดโทเค็นจากการตอบสนองแบบกระชับ)',
		vi: 'Trả về số liệu theo từng công cụ được thu thập trong tiến trình này: số lần gọi, lỗi, độ trễ tổng/tối đa (ms) và số byte phản hồi, cùng các tổng số. Chỉ đọc; truyền reset:true để đặt lại bộ đếm về 0 sau khi đọc, hoặc persist:true để lưu một snapshot có timestamp dưới <cacheDir>/metrics/ phục vụ so sánh theo thời gian. Định lượng chi phí công cụ (ví dụ: tiết kiệm token nhờ phản hồi gọn nhẹ).',
	},
};
