// i18n catalogue for `mcp-vertex_proposals_branch_gc`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const proposalsBranchGcI18n: IToolI18n = {
	description: {
		en: 'Idempotent cleanup of worktrees that have decayed into orphan state. A worktree is eligible when its branch is merged into baseBranch (default develop), its working tree is clean, and the last commit is older than staleMinutes (default 60). Defaults to dryRun: true; pass dryRun: false to actually execute. force: true allows removal of dirty worktrees (unmerged branches are still refused — that is sacred). Never pushes.',
		es: 'Limpieza idempotente de worktrees que han decaído a estado huérfano. Un worktree es elegible cuando su rama está fusionada en baseBranch (por defecto develop), su árbol de trabajo está limpio, y el último commit es más antiguo que staleMinutes (por defecto 60). Por defecto dryRun: true; pasa dryRun: false para ejecutar de verdad. force: true permite eliminar worktrees dirty (las ramas sin fusionar siguen rechazándose — eso es sagrado). Nunca hace push.',
		fr: "Nettoyage idempotent des worktrees qui ont dévié vers un état orphelin. Un worktree est éligible quand sa branche est fusionnée dans baseBranch (develop par défaut), que son arbre de travail est propre, et que le dernier commit est plus ancien que staleMinutes (60 par défaut). dryRun: true par défaut ; passez dryRun: false pour exécuter. force: true permet de supprimer des worktrees dirty (les branches non fusionnées restent refusées — c'est sacré). Ne pousse jamais.",
		de: 'Idempotente Bereinigung von Worktrees, die in einen verwaisten Zustand verfallen sind. Ein Worktree ist berechtigt, wenn sein Branch in baseBranch (Standard develop) gemergt wurde, der Arbeitsbaum sauber ist und der letzte Commit älter als staleMinutes (Standard 60) ist. Standard ist dryRun: true; übergib dryRun: false, um wirklich auszuführen. force: true erlaubt das Entfernen verschmutzter Worktrees (nicht gemergte Branches werden weiterhin abgelehnt — das ist unantastbar). Pusht nie.',
		it: "Pulizia idempotente dei worktree decaduti in stato orfano. Un worktree è idoneo quando il suo branch è unito in baseBranch (default develop), il suo albero di lavoro è pulito, e l'ultimo commit è più vecchio di staleMinutes (default 60). Default dryRun: true; passa dryRun: false per eseguire. force: true consente la rimozione di worktree dirty (i branch non uniti sono ancora rifiutati — è sacro). Non fa mai push.",
		pt: 'Limpeza idempotente de worktrees que decaíram em estado órfão. Um worktree é elegível quando seu branch está mergeado em baseBranch (padrão develop), sua árvore de trabalho está limpa, e o último commit é mais antigo que staleMinutes (padrão 60). Padrão dryRun: true; passe dryRun: false para executar de fato. force: true permite a remoção de worktrees dirty (branches não mergeados ainda são recusados — isso é sagrado). Nunca faz push.',
		ja: '孤立状態に陥った worktree を冪等にクリーンアップします。worktree は、ブランチが baseBranch(デフォルト develop)にマージ済みで、作業ツリーがクリーン、かつ最後のコミットが staleMinutes(デフォルト 60)より古い場合に削除対象となります。デフォルトは dryRun: true。dryRun: false を渡すと実際に実行されます。force: true で dirty な worktree の削除を許可します(未マージのブランチは引き続き拒否されます — それは神聖です)。プッシュは一切行いません。',
		zh: '对已退化为孤立状态的 worktree 进行幂等清理。当 worktree 的分支已合并到 baseBranch(默认为 develop)、工作树干净、且最后提交早于 staleMinutes(默认为 60)时,它才符合条件。默认为 dryRun: true;传入 dryRun: false 以真正执行。force: true 允许移除 dirty 的 worktree(未合并的分支仍然会被拒绝 — 这是不可逾越的红线)。绝不推送。',
		hi: 'जो worktrees अनाथ स्थिति में आ गए हैं उनकी idempotent सफ़ाई। एक worktree तब पात्र होता है जब उसकी ब्रांच baseBranch (डिफ़ॉल्ट develop) में मर्ज हो चुकी हो, उसका कार्य-वृक्ष साफ़ हो, और अंतिम कमिट staleMinutes (डिफ़ॉल्ट 60) से पुराना हो। डिफ़ॉल्ट dryRun: true; वास्तव में निष्पादित करने के लिए dryRun: false पास करें। force: true dirty worktrees को हटाने की अनुमति देता है (अनमर्ज्ड ब्रांचेस अभी भी अस्वीकृत हैं — यह पवित्र है)। कभी push नहीं करता।',
		ar: 'تنظيف متكرّر الأثر (idempotent) لـ worktrees التي تدهورت إلى حالة يتيمة. يكون worktree مؤهلاً عندما يكون فروعه مدمجًا في baseBranch (الافتراضي develop)، وتكون شجرة العمل نظيفة، ويكون آخر التزام أقدم من staleMinutes (الافتراضي 60). الافتراضي dryRun: true؛ مرّر dryRun: false للتنفيذ فعلاً. يسمح force: true بإزالة worktrees المتّسخة (لا تزال الفروع غير المدمجة مرفوضة — هذا مقدّس). لا يقوم بالدفع أبدًا.',
		th: 'การทำความสะอาดแบบ idempotent สำหรับ worktree ที่เสื่อมลงเป็นสถานะกำพร้า worktree จะมีสิทธิ์เมื่อสาขาของมันถูก merge เข้ากับ baseBranch (ค่าเริ่มต้น develop) ต้นไม้ทำงานสะอาด และคอมมิตล่าสุดเก่ากว่า staleMinutes (ค่าเริ่มต้น 60) ค่าเริ่มต้นคือ dryRun: true ส่ง dryRun: false เพื่อดำเนินการจริง force: true อนุญาตให้ลบ worktree ที่ dirty (สาขาที่ยังไม่ merge จะถูกปฏิเสธเสมอ — สิ่งนี้ศักดิ์สิทธิ์) ไม่ push เลย',
		vi: 'Dọn dẹp idempotent các worktree đã rơi vào trạng thái mồ côi. Một worktree đủ điều kiện khi nhánh của nó đã được merge vào baseBranch (mặc định develop), cây làm việc sạch, và commit gần nhất cũ hơn staleMinutes (mặc định 60). Mặc định dryRun: true; truyền dryRun: false để thực sự thực thi. force: true cho phép xóa các worktree dirty (các nhánh chưa merge vẫn bị từ chối — điều đó là thiêng liêng). Không bao giờ push.',
	},
};
