// i18n catalogue for `deps_deps_outdated`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const depsDepsOutdatedI18n: IToolI18n = {
	description: {
		en: "For each manifest dep whose range pins a plain x.y.z baseline, resolve the npm registry's `latest` dist-tag and flag it as outdated when newer. Ranges without a comparable baseline (*, latest, workspace:/npm:/file:/link:, git urls) report wanted:null and are skipped, not errors. Capped at 50 packages per call (truncated:true past the cap). Opt-in (plugins.deps.options.allowNetwork:true) — deps_list/deps_check stay offline.",
		es: 'Para cada dependencia del manifest cuyo rango fija una línea base x.y.z simple, resuelve la etiqueta de distribución `latest` del registro npm y la marca como obsoleta si hay una versión más nueva. Los rangos sin línea base comparable (*, latest, workspace:/npm:/file:/link:, URLs git) informan wanted:null y se omiten, no son errores. Limitado a 50 paquetes por llamada (truncated:true al superar el límite). Opcional (plugins.deps.options.allowNetwork:true) — deps_list/deps_check permanecen sin conexión.',
		fr: 'Pour chaque dépendance du manifeste dont la plage fixe une base x.y.z simple, résout le dist-tag `latest` du registre npm et la signale comme obsolète si une version plus récente existe. Les plages sans base comparable (*, latest, workspace:/npm:/file:/link:, URLs git) renvoient wanted:null et sont ignorées, pas des erreurs. Plafonné à 50 paquets par appel (truncated:true au-delà). Opt-in (plugins.deps.options.allowNetwork:true) — deps_list/deps_check restent hors ligne.',
		de: 'Für jede Manifest-Abhängigkeit, deren Bereich eine einfache x.y.z-Basis fixiert, wird der `latest`-Dist-Tag der npm-Registry aufgelöst und als veraltet markiert, wenn eine neuere Version existiert. Bereiche ohne vergleichbare Basis (*, latest, workspace:/npm:/file:/link:, Git-URLs) melden wanted:null und werden übersprungen, keine Fehler. Begrenzt auf 50 Pakete pro Aufruf (truncated:true über dem Limit). Opt-in (plugins.deps.options.allowNetwork:true) — deps_list/deps_check bleiben offline.',
		it: 'Per ogni dipendenza del manifest il cui intervallo fissa una baseline x.y.z semplice, risolve il dist-tag `latest` del registro npm e la segnala come obsoleta se esiste una versione più recente. Gli intervalli senza baseline comparabile (*, latest, workspace:/npm:/file:/link:, URL git) riportano wanted:null e vengono saltati, non sono errori. Limitato a 50 pacchetti per chiamata (truncated:true oltre il limite). Opt-in (plugins.deps.options.allowNetwork:true) — deps_list/deps_check restano offline.',
		pt: 'Para cada dependência do manifesto cujo intervalo fixa uma baseline x.y.z simples, resolve a dist-tag `latest` do registo npm e marca-a como obsoleta se houver uma versão mais recente. Intervalos sem baseline comparável (*, latest, workspace:/npm:/file:/link:, URLs git) reportam wanted:null e são ignorados, não são erros. Limitado a 50 pacotes por chamada (truncated:true acima do limite). Opt-in (plugins.deps.options.allowNetwork:true) — deps_list/deps_check permanecem offline.',
		ja: 'マニフェストの各依存関係について、範囲が単純な x.y.z ベースラインを固定している場合、npm レジストリの `latest` dist-tag を解決し、新しいバージョンがあれば古いとフラグを立てます。比較可能なベースラインのない範囲(*, latest, workspace:/npm:/file:/link:、git URL)は wanted:null を報告してスキップされ、エラーにはなりません。1 回の呼び出しで最大 50 パッケージ(上限超過時は truncated:true)。オプトイン(plugins.deps.options.allowNetwork:true) — deps_list/deps_check はオフラインのままです。',
		zh: '对于清单中范围固定为纯 x.y.z 基线的每个依赖项,解析 npm 注册表的 `latest` dist-tag,如有更新版本则标记为过期。没有可比较基线的范围(*、latest、workspace:/npm:/file:/link:、git url)会报告 wanted:null 并被跳过,不算错误。每次调用上限 50 个包(超出上限时 truncated:true)。需主动开启(plugins.deps.options.allowNetwork:true)——deps_list/deps_check 保持离线。',
		hi: 'मैनिफ़ेस्ट की हर निर्भरता के लिए जिसकी रेंज एक सादा x.y.z बेसलाइन पिन करती है, npm रजिस्ट्री के `latest` डिस्ट-टैग को हल करता है और नया होने पर इसे पुराना (outdated) चिह्नित करता है। तुलनीय बेसलाइन के बिना रेंज (*, latest, workspace:/npm:/file:/link:, git urls) wanted:null रिपोर्ट करती हैं और छोड़ दी जाती हैं, ये त्रुटियाँ नहीं हैं। प्रति कॉल अधिकतम 50 पैकेज (सीमा से ऊपर truncated:true)। ऑप्ट-इन (plugins.deps.options.allowNetwork:true) — deps_list/deps_check ऑफ़लाइन ही रहते हैं।',
		ar: 'لكل تبعية في المانيفست يثبّت نطاقها خط أساس x.y.z بسيط، يحل علامة التوزيع `latest` من سجل npm ويعلّمها كقديمة إذا كانت هناك نسخة أحدث. النطاقات التي لا تملك خط أساس قابل للمقارنة (*, latest, workspace:/npm:/file:/link:, روابط git) تُرجع wanted:null ويتم تجاوزها، وليست أخطاء. الحد الأقصى 50 حزمة لكل استدعاء (truncated:true بعد تجاوز الحد). اختياري (plugins.deps.options.allowNetwork:true) — يبقى deps_list/deps_check دون اتصال.',
		th: 'สำหรับแต่ละดีเพนเดนซีในแมนิเฟสต์ที่ช่วงเวอร์ชันตรึงเบสไลน์ x.y.z แบบธรรมดา จะแก้ไข dist-tag `latest` จากรีจิสทรี npm และตั้งค่าสถานะว่าล้าสมัยเมื่อมีเวอร์ชันใหม่กว่า ช่วงที่ไม่มีเบสไลน์ที่เทียบได้ (*, latest, workspace:/npm:/file:/link:, git urls) จะรายงาน wanted:null และถูกข้าม ไม่ถือเป็นข้อผิดพลาด จำกัดที่ 50 แพ็กเกจต่อการเรียก (truncated:true เมื่อเกินขีดจำกัด) ต้องเปิดใช้เอง (plugins.deps.options.allowNetwork:true) — deps_list/deps_check ยังคงออฟไลน์',
		vi: 'Với mỗi dependency trong manifest có dải phiên bản cố định một baseline x.y.z đơn giản, giải quyết dist-tag `latest` từ registry npm và đánh dấu lỗi thời nếu có phiên bản mới hơn. Các dải không có baseline so sánh được (*, latest, workspace:/npm:/file:/link:, git urls) báo cáo wanted:null và bị bỏ qua, không phải lỗi. Giới hạn 50 package mỗi lần gọi (truncated:true khi vượt giới hạn). Tùy chọn kích hoạt (plugins.deps.options.allowNetwork:true) — deps_list/deps_check vẫn ngoại tuyến.',
	},
};
