// i18n catalogue for `mcp-vertex_proposals_branch_status`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const proposalsBranchStatusI18n: IToolI18n = {
	description: {
		en: 'Read-only snapshot of every `agent/*` branch and every worktree in the workspace. Reports ahead/behind counts vs baseBranch (default develop), last-commit age, merged flag, and per-worktree dirty + untracked file counts. Worktrees whose path lives outside <cacheDir>/mcp-vertex/.worktrees are flagged `outOfCache: true`. Use this before merging, before pushing, or whenever the orchestrator needs to know what other agents are doing.',
		es: 'Instantánea de solo lectura de cada rama `agent/*` y cada worktree del espacio de trabajo. Informa recuentos ahead/behind frente a baseBranch (por defecto develop), edad del último commit, marca de merge y recuentos por worktree de archivos dirty + untracked. Los worktrees cuya ruta quede fuera de <cacheDir>/mcp-vertex/.worktrees se marcan como `outOfCache: true`. Úsalo antes de fusionar, antes de hacer push, o cuando el orquestador necesite saber qué hacen otros agentes.',
		fr: "Instantané en lecture seule de chaque branche `agent/*` et de chaque worktree de l'espace de travail. Rapporte les compteurs ahead/behind par rapport à baseBranch (develop par défaut), l'âge du dernier commit, l'indicateur de fusion, et les compteurs par worktree de fichiers dirty + untracked. Les worktrees dont le chemin est en dehors de <cacheDir>/mcp-vertex/.worktrees sont signalés par `outOfCache: true`. À utiliser avant un merge, avant un push, ou dès que l'orchestrateur a besoin de savoir ce que font les autres agents.",
		de: 'Schreibgeschützter Snapshot jedes `agent/*`-Branches und jedes Worktrees im Workspace. Meldet ahead/behind-Zähler gegenüber baseBranch (Standard develop), Alter des letzten Commits, Merge-Flag und pro Worktree Dirty- + Untracked-Dateizähler. Worktrees, deren Pfad außerhalb von <cacheDir>/mcp-vertex/.worktrees liegt, werden mit `outOfCache: true` markiert. Verwende dies vor einem Merge, vor einem Push, oder immer wenn der Orchestrator wissen muss, was andere Agenten tun.',
		it: "Snapshot in sola lettura di ogni branch `agent/*` e di ogni worktree nel workspace. Riporta i conteggi ahead/behind rispetto a baseBranch (default develop), età dell'ultimo commit, flag di merge e conteggi per worktree di file dirty + untracked. I worktree il cui percorso è esterno a <cacheDir>/mcp-vertex/.worktrees vengono marcati come `outOfCache: true`. Usalo prima di un merge, prima di un push, o quando l'orchestratore ha bisogno di sapere cosa fanno gli altri agenti.",
		pt: 'Snapshot somente leitura de cada branch `agent/*` e cada worktree no workspace. Reporta contagens ahead/behind em relação a baseBranch (padrão develop), idade do último commit, flag de merge e contagens por worktree de arquivos dirty + untracked. Worktrees cujo caminho esteja fora de <cacheDir>/mcp-vertex/.worktrees são marcados como `outOfCache: true`. Use isto antes de um merge, antes de um push, ou quando o orquestrador precisa saber o que os outros agentes estão fazendo.',
		ja: 'ワークスペース内のすべての `agent/*` ブランチとすべての worktree の読み取り専用スナップショット。baseBranch(デフォルトは develop)に対する ahead/behind 数、最新コミットの経過時間、マージ済みフラグ、worktree ごとの dirty + untracked ファイル数を報告します。<cacheDir>/mcp-vertex/.worktrees の外側にあるパスの worktree は `outOfCache: true` としてフラグ付けされます。マージ前、プッシュ前、またはオーケストレーターが他のエージェントの動きを知る必要があるときに使用してください。',
		zh: '工作区中每个 `agent/*` 分支和每个 worktree 的只读快照。报告相对于 baseBranch(默认为 develop) 的 ahead/behind 计数、最后提交的时间、合并标记,以及每个 worktree 的 dirty + untracked 文件计数。路径位于 <cacheDir>/mcp-vertex/.worktrees 之外的 worktree 会被标记为 `outOfCache: true`。在合并前、推送前,或编排器需要了解其他代理正在做什么时使用。',
		hi: 'वर्कस्पेस में हर `agent/*` ब्रांच और हर worktree का रीड-ओनली स्नैपशॉट। baseBranch (डिफ़ॉल्ट develop) के सापेक्ष ahead/behind काउंट, अंतिम कमिट की आयु, मर्ज फ़्लैग, और प्रति-worktree dirty + untracked फ़ाइल काउंट रिपोर्ट करता है। जिन worktrees का पथ <cacheDir>/mcp-vertex/.worktrees के बाहर है उन्हें `outOfCache: true` के रूप में फ़्लैग किया जाता है। मर्ज करने से पहले, पुश करने से पहले, या जब ऑर्केस्ट्रेटर को जानना हो कि अन्य एजेंट क्या कर रहे हैं, इसका उपयोग करें।',
		ar: 'لقطة قراءة فقط لكل فرع `agent/*` وكل worktree في مساحة العمل. تُبلّغ عن أعداد ahead/behind نسبةً إلى baseBranch (الافتراضي develop)، وعمر آخر التزام، وعلامة الدمج، وأعداد الملفات dirty + untracked لكل worktree. يتم وضع علامة `outOfCache: true` على أي worktree يقع مساره خارج <cacheDir>/mcp-vertex/.worktrees. استخدم هذا قبل الدمج، أو قبل الدفع، أو كلما احتاج المنسق إلى معرفة ما يفعله الوكلاء الآخرون.',
		th: 'สแนปช็อตแบบอ่านอย่างเดียวของทุกสาขา `agent/*` และทุก worktree ในพื้นที่ทำงาน รายงานจำนวน ahead/behind เทียบกับ baseBranch (ค่าเริ่มต้น develop) อายุของคอมมิตล่าสุด แฟลกการ merge และจำนวนไฟล์ dirty + untracked ต่อ worktree worktree ที่มีพาธอยู่นอก <cacheDir>/mcp-vertex/.worktrees จะถูกทำเครื่องหมายเป็น `outOfCache: true` ใช้สิ่งนี้ก่อน merge ก่อน push หรือเมื่อ orchestrator ต้องการรู้ว่าเอเจนต์อื่นกำลังทำอะไรอยู่',
		vi: 'Ảnh chụp chỉ-đọc của mọi nhánh `agent/*` và mọi worktree trong workspace. Báo cáo số lượng ahead/behind so với baseBranch (mặc định develop), tuổi của commit gần nhất, cờ merge, và số file dirty + untracked cho mỗi worktree. Các worktree có đường dẫn nằm ngoài <cacheDir>/mcp-vertex/.worktrees được gắn cờ `outOfCache: true`. Hãy dùng nó trước khi merge, trước khi push, hoặc bất cứ khi nào orchestrator cần biết các agent khác đang làm gì.',
	},
};
