// i18n catalogue for `mcp-vertex_proposals_swarm_hygiene`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const proposalsSwarmHygieneI18n: IToolI18n = {
	description: {
		en: "Read-only swarm hygiene snapshot. Returns three lists: rescueCandidates (agent/* branches with ahead>0 and not merged into develop — carries cherryPickHint + diffStat), gcEligible (the branch_gc dry-run plan), outOfCache (worktrees outside <cacheDir>/mcp-vertex/.worktrees). Use this before merging, before closing a session, or whenever the orchestrator wants to surface the swarm's rescue/cleanup opportunities without firing destructive tools.",
		es: 'Instantánea de solo lectura de higiene del enjambre. Devuelve tres listas: rescueCandidates (ramas agent/* con ahead>0 y no fusionadas en develop — incluye cherryPickHint + diffStat), gcEligible (el plan dry-run de branch_gc), outOfCache (worktrees fuera de <cacheDir>/mcp-vertex/.worktrees). Úsalo antes de fusionar, antes de cerrar una sesión, o cuando el orquestador quiera exponer las oportunidades de rescate/limpieza del enjambre sin activar herramientas destructivas.',
		fr: "Instantané en lecture seule d'hygiène de l'essaim. Renvoie trois listes : rescueCandidates (branches agent/* avec ahead>0 et non fusionnées dans develop — contient cherryPickHint + diffStat), gcEligible (le plan dry-run de branch_gc), outOfCache (worktrees hors de <cacheDir>/mcp-vertex/.worktrees). À utiliser avant un merge, avant de fermer une session, ou chaque fois que l'orchestrateur veut exposer les opportunités de sauvetage/nettoyage de l'essaim sans déclencher d'outils destructifs.",
		de: 'Schreibgeschützter Snapshot der Schwarm-Hygiene. Liefert drei Listen: rescueCandidates (agent/*-Branches mit ahead>0 und nicht in develop gemergt — mit cherryPickHint + diffStat), gcEligible (der branch_gc-Trockenlauf-Plan), outOfCache (Worktrees außerhalb von <cacheDir>/mcp-vertex/.worktrees). Verwende dies vor einem Merge, vor dem Schließen einer Sitzung oder immer wenn der Orchestrator die Rescue-/Cleanup-Möglichkeiten des Schwarms sichtbar machen will, ohne destruktive Tools auszulösen.',
		it: "Snapshot di sola lettura dell'igiene dello sciame. Restituisce tre elenchi: rescueCandidates (branch agent/* con ahead>0 e non unite in develop — include cherryPickHint + diffStat), gcEligible (il piano dry-run di branch_gc), outOfCache (worktree fuori da <cacheDir>/mcp-vertex/.worktrees). Usalo prima di un merge, prima di chiudere una sessione, o quando l'orchestratore vuole esporre le opportunità di salvataggio/pulizia dello sciame senza attivare strumenti distruttivi.",
		pt: 'Snapshot somente leitura da higiene do enxame. Retorna três listas: rescueCandidates (branches agent/* com ahead>0 e não mergeadas em develop — inclui cherryPickHint + diffStat), gcEligible (o plano dry-run de branch_gc), outOfCache (worktrees fora de <cacheDir>/mcp-vertex/.worktrees). Use isto antes de um merge, antes de fechar uma sessão, ou quando o orquestrador precisa expor as oportunidades de resgate/limpeza do enxame sem disparar ferramentas destrutivas.',
		ja: 'スウォーム衛生の読み取り専用スナップショット。3 つのリストを返します:rescueCandidates(develop に未マージで ahead>0 の agent/* ブランチ — cherryPickHint + diffStat を含む)、gcEligible(branch_gc の dry-run プラン)、outOfCache(<cacheDir>/mcp-vertex/.worktrees の外側にある worktree)。マージ前、セッションクローズ前、またはオーケストレーターが破壊的ツールを起動せずにスウォームの救出/クリーンアップ機会を提示したい場合に使用してください。',
		zh: '群卫生的只读快照。返回三个列表:rescueCandidates(有 ahead>0 且未合并到 develop 的 agent/* 分支 — 包含 cherryPickHint + diffStat)、gcEligible(branch_gc 的 dry-run 计划)、outOfCache(<cacheDir>/mcp-vertex/.worktrees 之外的 worktree)。在合并前、关闭会话前,或编排器需要展示群中的救援/清理机会而不触发破坏性工具时使用。',
		hi: 'स्वॉर्म हाइजीन का रीड-ओनली स्नैपशॉट। तीन सूचियाँ लौटाता है:rescueCandidates(develop में अनमर्ज्ड और ahead>0 वाली agent/* ब्रांचेस — cherryPickHint + diffStat के साथ), gcEligible(branch_gc dry-run प्लान), outOfCache(<cacheDir>/mcp-vertex/.worktrees के बाहर के worktrees)। मर्ज करने से पहले, सेशन बंद करने से पहले, या जब ऑर्केस्ट्रेटर को स्वॉर्म के रेस्क्यू/क्लीनअप अवसरों को दिखाना हो (बिना विनाशकारी टूल्स चलाए) — इसका उपयोग करें।',
		ar: 'لقطة قراءة فقط لنظافة السرب. تُرجع ثلاث قوائم: rescueCandidates (فروع agent/* ذات ahead>0 وغير مدمجة في develop — تتضمن cherryPickHint + diffStat)، gcEligible (خطة dry-run لـ branch_gc)، outOfCache (worktrees خارج <cacheDir>/mcp-vertex/.worktrees). استخدم هذا قبل الدمج، أو قبل إغلاق جلسة، أو كلما أراد المنسق عرض فرص الإنقاذ/التنظيف في السرب دون تشغيل أدوات مدمّرة.',
		th: 'สแนปช็อตแบบอ่านอย่างเดียวของสุขอนามัยของสวอร์ม ส่งคืนสามรายการ: rescueCandidates (สาขา agent/* ที่มี ahead>0 และยังไม่ได้ merge เข้ากับ develop — พร้อม cherryPickHint + diffStat), gcEligible (แผน dry-run ของ branch_gc), outOfCache (worktree ที่อยู่นอก <cacheDir>/mcp-vertex/.worktrees) ใช้สิ่งนี้ก่อน merge ก่อนปิดเซสชัน หรือเมื่อ orchestrator ต้องการแสดงโอกาสในการช่วยเหลือ/ทำความสะอาดของสวอร์มโดยไม่เรียกเครื่องมือที่ทำลาย',
		vi: 'Ảnh chụp chỉ-đọc về vệ sinh swarm. Trả về ba danh sách: rescueCandidates (các nhánh agent/* có ahead>0 và chưa merge vào develop — kèm cherryPickHint + diffStat), gcEligible (kế hoạch dry-run của branch_gc), outOfCache (các worktree nằm ngoài <cacheDir>/mcp-vertex/.worktrees). Hãy dùng trước khi merge, trước khi đóng phiên, hoặc bất cứ khi nào orchestrator muốn hiển thị các cơ hội cứu hộ/dọn dẹp của swarm mà không kích hoạt các công cụ phá hoại.',
	},
};
