// i18n catalogue for `proposals_proposal_review`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const proposalsProposalReviewI18n: IToolI18n = {
	description: {
		en: 'Peer-review loop for a slice. action=submit: an implementer marks a finished slice ready for review (not done yet). action=approve: a DIFFERENT agent verifies and approves it → slice is set done + lock released. action=request_changes (note required): a different agent records an objection → slice becomes reworkable + lock released; the fixer re-submits and another agent reviews the fix. action=status: read current state. Enforces reviewer ≠ implementer (independent verification).',
		es: 'Bucle de revisión por pares para un slice. action=submit: un implementador marca un slice terminado como listo para revisión (todavía no done). action=approve: un agente DIFERENTE lo verifica y aprueba → el slice se marca done + se libera el lock. action=request_changes (nota obligatoria): un agente distinto registra una objeción → el slice pasa a reworkable + se libera el lock; quien lo corrige lo vuelve a enviar y otro agente revisa la corrección. action=status: lee el estado actual. Impone que revisor ≠ implementador (verificación independiente).',
		fr: "Boucle de revue par les pairs pour une tranche. action=submit : un implémenteur marque une tranche terminée comme prête pour revue (pas encore done). action=approve : un agent DIFFÉRENT la vérifie et l'approuve → la tranche est marquée done + le verrou est libéré. action=request_changes (note requise) : un agent différent enregistre une objection → la tranche devient reworkable + le verrou est libéré ; le correcteur la resoumet et un autre agent revoit le correctif. action=status : lit l'état actuel. Impose réviseur ≠ implémenteur (vérification indépendante).",
		de: 'Peer-Review-Schleife für eine Slice. action=submit: ein Implementierer markiert eine fertige Slice als bereit zur Überprüfung (noch nicht done). action=approve: ein ANDERER Agent verifiziert und genehmigt sie → Slice wird auf done gesetzt + Sperre freigegeben. action=request_changes (Hinweis erforderlich): ein anderer Agent erfasst einen Einwand → Slice wird reworkable + Sperre wird freigegeben; der Fixer reicht erneut ein und ein anderer Agent prüft die Korrektur. action=status: liest den aktuellen Zustand. Erzwingt Reviewer ≠ Implementierer (unabhängige Verifizierung).',
		it: 'Ciclo di peer-review per una slice. action=submit: un implementatore segna una slice completata come pronta per la revisione (non ancora done). action=approve: un agente DIVERSO la verifica e la approva → la slice viene impostata su done + il lock viene rilasciato. action=request_changes (nota obbligatoria): un agente diverso registra un obiezione → la slice diventa reworkable + il lock viene rilasciato; chi corregge la ripresenta e un altro agente revisiona la correzione. action=status: legge lo stato attuale. Impone revisore ≠ implementatore (verifica indipendente).',
		pt: 'Ciclo de peer-review para uma slice. action=submit: um implementador marca uma slice concluída como pronta para revisão (ainda não done). action=approve: um agente DIFERENTE verifica-a e aprova-a → a slice é definida como done + o lock é libertado. action=request_changes (nota obrigatória): um agente diferente regista uma objeção → a slice passa a reworkable + o lock é libertado; quem corrige volta a submeter e outro agente revisa a correção. action=status: lê o estado atual. Impõe revisor ≠ implementador (verificação independente).',
		ja: 'スライスのピアレビューループ。action=submit:実装者が完成したスライスをレビュー準備完了としてマークします(まだ done ではありません)。action=approve:別のエージェントが検証して承認します → スライスは done に設定され、ロックが解放されます。action=request_changes(note 必須):別のエージェントが異論を記録します → スライスは reworkable になり、ロックが解放されます;修正者が再提出し、別のエージェントが修正をレビューします。action=status:現在の状態を読み取ります。レビュアー ≠ 実装者(独立検証)を強制します。',
		zh: '切片的同行评审循环。action=submit:实施者将完成的切片标记为待审核(尚未完成)。action=approve:另一位不同的代理验证并批准 → 切片被设为完成 + 释放锁。action=request_changes(必须填写备注):另一位代理记录异议 → 切片变为可重做状态 + 释放锁;修复者重新提交,由另一位代理审核修复结果。action=status:读取当前状态。强制要求审核者 ≠ 实施者(独立验证)。',
		hi: 'किसी स्लाइस के लिए पीयर-रिव्यू लूप। action=submit: एक इम्प्लीमेंटर एक पूर्ण स्लाइस को रिव्यू के लिए तैयार चिह्नित करता है (अभी done नहीं)। action=approve: एक भिन्न एजेंट इसे सत्यापित करता है और मंज़ूर करता है → स्लाइस को done सेट किया जाता है + लॉक रिलीज़ होता है। action=request_changes (नोट आवश्यक): एक भिन्न एजेंट आपत्ति दर्ज करता है → स्लाइस reworkable बन जाता है + लॉक रिलीज़ होता है; फिक्सर इसे फिर से सबमिट करता है और दूसरा एजेंट फिक्स की समीक्षा करता है। action=status: वर्तमान स्थिति पढ़ता है। रिव्यूअर ≠ इम्प्लीमेंटर (स्वतंत्र सत्यापन) को लागू करता है।',
		ar: 'حلقة مراجعة من الأقران لشريحة. action=submit: يُعلِم منفِّذ شريحة منتهية بأنها جاهزة للمراجعة (ليست done بعد). action=approve: يتحقق منها ويوافق عليها وكيل مختلف ← يتم تعيين الشريحة كـ done + تحرير القفل. action=request_changes (الملاحظة مطلوبة): يسجل وكيل مختلف اعتراضًا ← تصبح الشريحة قابلة لإعادة العمل + يُحرر القفل؛ يعيد المُصحِّح تقديمها ويراجع وكيل آخر الإصلاح. action=status: يقرأ الحالة الحالية. يفرض أن يكون المراجع ≠ المنفِّذ (تحقق مستقل).',
		th: 'วงจรการรีวิวจากเพื่อนร่วมงานสำหรับสไลซ์ action=submit: ผู้ดำเนินการทำเครื่องหมายสไลซ์ที่เสร็จแล้วว่าพร้อมสำหรับการรีวิว (ยังไม่ done) action=approve: เอเจนต์ที่แตกต่างกันตรวจสอบและอนุมัติ → สไลซ์ถูกตั้งเป็น done + ปล่อยล็อก action=request_changes (ต้องมีบันทึก): เอเจนต์ที่แตกต่างกันบันทึกข้อโต้แย้ง → สไลซ์กลายเป็น reworkable + ปล่อยล็อก ผู้แก้ไขส่งใหม่และเอเจนต์อื่นรีวิวการแก้ไข action=status: อ่านสถานะปัจจุบัน บังคับให้ผู้รีวิว ≠ ผู้ดำเนินการ (การตรวจสอบที่เป็นอิสระ)',
		vi: 'Vòng đánh giá ngang hàng cho một lát. action=submit: người triển khai đánh dấu một lát đã hoàn thành là sẵn sàng để xem xét (chưa phải done). action=approve: một agent KHÁC xác minh và phê duyệt nó → lát được đặt là done + lock được giải phóng. action=request_changes (cần ghi chú): một agent khác ghi nhận phản đối → lát trở thành reworkable + lock được giải phóng; người sửa nộp lại và một agent khác xem xét bản sửa. action=status: đọc trạng thái hiện tại. Bắt buộc người đánh giá ≠ người triển khai (xác minh độc lập).',
	},
};
