// i18n catalogue for `proposals_proposal_adopt`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const proposalsProposalAdoptI18n: IToolI18n = {
	description: {
		en: 'Make a proposals folder followable. Returns the canonical layout (index.json, README, p<N>/f<N> files, done/ + host buckets), a scan of the actual folder (proposals/fixes with status, subfolders, files without proposal frontmatter, missing index/README) and an ordered plan to organize it for mcp-vertex. Read-only — it advises; you run the steps. Pass `dir` (workspace-relative) to analyze a folder other than the configured proposals dir.',
		es: 'Hace que una carpeta de proposals sea seguible. Devuelve la estructura canónica (index.json, README, ficheros p<N>/f<N>, done/ + buckets de host), un escaneo de la carpeta real (proposals/fixes con estado, subcarpetas, ficheros sin frontmatter de propuesta, index/README ausentes) y un plan ordenado para organizarla para mcp-vertex. Solo lectura — asesora; tú ejecutas los pasos. Pasa `dir` (relativo al workspace) para analizar una carpeta distinta a la configurada para proposals.',
		fr: "Rend un dossier de proposals suivable. Renvoie la disposition canonique (index.json, README, fichiers p<N>/f<N>, done/ + buckets hôte), une analyse du dossier réel (proposals/fixes avec statut, sous-dossiers, fichiers sans frontmatter de proposition, index/README manquants) et un plan ordonné pour l'organiser pour mcp-vertex. Lecture seule — il conseille ; vous exécutez les étapes. Passez `dir` (relatif à l'espace de travail) pour analyser un dossier autre que celui configuré pour proposals.",
		de: 'Macht einen Proposals-Ordner verfolgbar. Gibt das kanonische Layout zurück (index.json, README, p<N>/f<N>-Dateien, done/ + Host-Buckets), einen Scan des tatsächlichen Ordners (proposals/fixes mit Status, Unterordner, Dateien ohne Proposal-Frontmatter, fehlendes index/README) und einen geordneten Plan, um ihn für mcp-vertex zu organisieren. Nur lesend — es berät; du führst die Schritte aus. Übergib `dir` (workspace-relativ), um einen anderen als den konfigurierten Proposals-Ordner zu analysieren.',
		it: 'Rende un cartella proposals seguibile. Restituisce il layout canonico (index.json, README, file p<N>/f<N>, done/ + bucket host), una scansione della cartella reale (proposals/fixes con stato, sottocartelle, file senza frontmatter di proposta, index/README mancanti) e un piano ordinato per organizzarla per mcp-vertex. Solo lettura — consiglia; tu esegui i passaggi. Passa `dir` (relativo al workspace) per analizzare una cartella diversa da quella configurata per proposals.',
		pt: 'Torna uma pasta de proposals seguível. Devolve o layout canónico (index.json, README, ficheiros p<N>/f<N>, done/ + buckets de host), uma análise da pasta real (proposals/fixes com estado, subpastas, ficheiros sem frontmatter de proposta, index/README em falta) e um plano ordenado para a organizar para o mcp-vertex. Apenas leitura — aconselha; tu executas os passos. Passa `dir` (relativo ao workspace) para analisar uma pasta diferente da configurada para proposals.',
		ja: 'proposals フォルダを追跡可能にします。正規のレイアウト(index.json、README、p<N>/f<N> ファイル、done/ + ホストバケット)、実際のフォルダのスキャン(ステータス付きの proposals/fixes、サブフォルダ、提案 frontmatter のないファイル、index/README の欠落)、および mcp-vertex 用に整理するための順序付けられたプランを返します。読み取り専用 — 助言のみ;手順の実行はあなたが行います。設定された proposals ディレクトリ以外のフォルダを分析するには `dir`(workspace 相対)を渡します。',
		zh: '使一个 proposals 文件夹可被跟踪。返回规范布局(index.json、README、p<N>/f<N> 文件、done/ + 宿主分桶),对实际文件夹的扫描结果(带状态的 proposals/fixes、子文件夹、没有提案 frontmatter 的文件、缺失的 index/README),以及为 mcp-vertex 组织它的有序计划。只读——它提供建议;你来执行这些步骤。传入 `dir`(相对于工作区)以分析与已配置 proposals 目录不同的文件夹。',
		hi: 'किसी proposals फ़ोल्डर को फॉलो किए जाने योग्य बनाता है। कैनोनिकल लेआउट लौटाता है (index.json, README, p<N>/f<N> फ़ाइलें, done/ + होस्ट बकेट्स), वास्तविक फ़ोल्डर का स्कैन (स्टेटस के साथ proposals/fixes, सबफ़ोल्डर्स, प्रस्ताव frontmatter के बिना फ़ाइलें, गुम index/README), और mcp-vertex के लिए इसे संगठित करने हेतु एक क्रमबद्ध योजना। केवल पढ़ने के लिए — यह सलाह देता है; आप चरण चलाते हैं। कॉन्फ़िगर किए गए proposals डायरेक्टरी के अलावा किसी फ़ोल्डर का विश्लेषण करने के लिए `dir` (वर्कस्पेस-सापेक्ष) पास करें।',
		ar: 'يجعل مجلد proposals قابلاً للتتبع. يُرجع المخطط المعياري (index.json، README، ملفات p<N>/f<N>، done/ + حاويات المضيف)، ومسحًا للمجلد الفعلي (proposals/fixes مع الحالة، المجلدات الفرعية، الملفات بدون frontmatter اقتراح، index/README المفقودين) وخطة مرتبة لتنظيمه لـ mcp-vertex. للقراءة فقط — ينصح فقط؛ أنت من ينفذ الخطوات. مرّر `dir` (نسبي لمساحة العمل) لتحليل مجلد آخر غير دليل proposals المُهيَّأ.',
		th: 'ทำให้โฟลเดอร์ proposals สามารถติดตามได้ ส่งคืนโครงร่างมาตรฐาน (index.json, README, ไฟล์ p<N>/f<N>, done/ + บัคเก็ตของโฮสต์) การสแกนโฟลเดอร์จริง (proposals/fixes พร้อมสถานะ โฟลเดอร์ย่อย ไฟล์ที่ไม่มี frontmatter ของข้อเสนอ index/README ที่ขาดหายไป) และแผนที่จัดลำดับเพื่อจัดระเบียบสำหรับ mcp-vertex อ่านอย่างเดียว — มันให้คำแนะนำ คุณเป็นผู้ดำเนินขั้นตอน ส่ง `dir` (สัมพัทธ์กับเวิร์กสเปซ) เพื่อวิเคราะห์โฟลเดอร์อื่นที่ไม่ใช่ไดเรกทอรี proposals ที่กำหนดไว้',
		vi: 'Làm cho một thư mục proposals có thể theo dõi được. Trả về bố cục chuẩn (index.json, README, các tệp p<N>/f<N>, done/ + các bucket host), một bản quét thư mục thực tế (proposals/fixes kèm trạng thái, thư mục con, các tệp không có frontmatter đề xuất, thiếu index/README) và một kế hoạch có thứ tự để tổ chức nó cho mcp-vertex. Chỉ đọc — nó đưa ra lời khuyên; bạn thực hiện các bước. Truyền `dir` (tương đối với workspace) để phân tích một thư mục khác với thư mục proposals đã cấu hình.',
	},
};
