// i18n catalogue for `test-convention_scan_drift`.

import type { IToolI18n } from '#I18N/tools/_shape';

export const testConventionScanDriftI18n: IToolI18n = {
	description: {
		en: 'Scans `src/` and `tests/` (or just one of them with `scope`) for violations of the canonical test convention: wrong spec extension, missing spec companion, orphan imports, missing top-level describe, forbidden patterns (.only, xit, @ts-ignore, console.log), wrong mock API, empty describe names. Returns a structured report; `ok === true` only when there are zero errors.',
		es: 'Escanea `src/` y `tests/` (o solo uno de ellos con `scope`) buscando violaciones de la convención canónica de tests: extensión de spec incorrecta, spec compañero ausente, imports huérfanos, describe de nivel superior ausente, patrones prohibidos (.only, xit, @ts-ignore, console.log), API de mock incorrecta, nombres de describe vacíos. Devuelve un informe estructurado; `ok === true` solo cuando hay cero errores.',
		fr: "Analyse `src/` et `tests/` (ou un seul des deux avec `scope`) pour détecter les violations de la convention de test canonique : mauvaise extension de spec, spec compagnon manquant, imports orphelins, describe de premier niveau manquant, motifs interdits (.only, xit, @ts-ignore, console.log), mauvaise API de mock, noms de describe vides. Renvoie un rapport structuré ; `ok === true` uniquement lorsqu'il y a zéro erreur.",
		de: 'Durchsucht `src/` und `tests/` (oder nur eines davon mit `scope`) nach Verstößen gegen die kanonische Testkonvention: falsche Spec-Erweiterung, fehlendes Spec-Pendant, verwaiste Importe, fehlendes Top-Level-describe, verbotene Muster (.only, xit, @ts-ignore, console.log), falsche Mock-API, leere describe-Namen. Gibt einen strukturierten Bericht zurück; `ok === true` nur, wenn null Fehler vorliegen.',
		it: 'Scansiona `src/` e `tests/` (o solo uno di essi con `scope`) per violazioni della convenzione di test canonica: estensione spec errata, spec companion mancante, import orfani, describe di primo livello mancante, pattern proibiti (.only, xit, @ts-ignore, console.log), API mock errata, nomi describe vuoti. Restituisce un report strutturato; `ok === true` solo quando ci sono zero errori.',
		pt: 'Analisa `src/` e `tests/` (ou apenas um deles com `scope`) à procura de violações da convenção de testes canónica: extensão de spec errada, spec companion em falta, imports órfãos, describe de nível superior em falta, padrões proibidos (.only, xit, @ts-ignore, console.log), API de mock errada, nomes de describe vazios. Devolve um relatório estruturado; `ok === true` apenas quando há zero erros.',
		ja: '`src/` と `tests/`(または `scope` でいずれか一方のみ)をスキャンし、正規のテスト規約への違反を検出します:誤った spec 拡張子、対応する spec の欠落、孤立した import、トップレベル describe の欠落、禁止パターン(.only, xit, @ts-ignore, console.log)、誤った mock API、空の describe 名。構造化されたレポートを返します;エラーがゼロの場合のみ `ok === true` になります。',
		zh: '扫描 `src/` 和 `tests/`(或通过 `scope` 仅扫描其中之一),检测是否违反规范测试约定:spec 扩展名错误、缺少对应的 spec 文件、孤立的导入、缺少顶层 describe、禁止的模式(.only、xit、@ts-ignore、console.log)、错误的 mock API、空的 describe 名称。返回结构化报告;仅当零错误时 `ok === true`。',
		hi: '`src/` और `tests/` को स्कैन करता है (या `scope` के साथ केवल एक को) कैनोनिकल टेस्ट परंपरा के उल्लंघनों के लिए: गलत स्पेक एक्सटेंशन, गुम स्पेक कंपेनियन, अनाथ इम्पोर्ट्स, गुम टॉप-लेवल describe, प्रतिबंधित पैटर्न (.only, xit, @ts-ignore, console.log), गलत मॉक API, खाली describe नाम। एक संरचित रिपोर्ट लौटाता है; `ok === true` केवल तब जब शून्य त्रुटियाँ हों।',
		ar: 'يفحص `src/` و `tests/` (أو واحدًا منهما فقط باستخدام `scope`) بحثًا عن مخالفات اتفاقية الاختبار المعيارية: امتداد spec خاطئ، رفيق spec مفقود، استيرادات يتيمة، describe على المستوى الأعلى مفقود، أنماط محظورة (.only، xit، @ts-ignore، console.log)، واجهة محاكاة خاطئة، أسماء describe فارغة. يُرجع تقريرًا منظمًا؛ `ok === true` فقط عندما يكون عدد الأخطاء صفرًا.',
		th: 'สแกน `src/` และ `tests/` (หรือเฉพาะหนึ่งในนั้นด้วย `scope`) เพื่อหาการละเมิดข้อตกลงการทดสอบมาตรฐาน: นามสกุล spec ผิด, ไม่มี spec companion, import ที่ไม่มีเจ้าของ, ไม่มี describe ระดับบนสุด, รูปแบบที่ห้ามใช้ (.only, xit, @ts-ignore, console.log), mock API ผิด, ชื่อ describe ว่าง ส่งคืนรายงานที่มีโครงสร้าง `ok === true` เฉพาะเมื่อไม่มีข้อผิดพลาดเลย',
		vi: 'Quét `src/` và `tests/` (hoặc chỉ một trong hai với `scope`) để tìm các vi phạm quy ước kiểm thử chuẩn: sai phần mở rộng spec, thiếu spec đi kèm, import bị bỏ rơi, thiếu describe cấp cao nhất, các mẫu bị cấm (.only, xit, @ts-ignore, console.log), sai mock API, tên describe trống. Trả về báo cáo có cấu trúc; `ok === true` chỉ khi có 0 lỗi.',
	},
};
