/**
 * static-rules.ts — the built-in eviction rules the `@mcp-vertex/cache`
 * plugin contributes to the core {@link ICacheEvictionRegistry}.
 *
 * Every rule is DATA: it names a path under `<cacheDir>` and a `when`
 * strategy. The registry (in `@mcp-vertex/core`) owns the apply logic;
 * this module owns only the policy (which artefacts, how old). Adding a
 * new built-in rule is a new entry here — no consumer changes (OCP).
 *
 * Defaults mirror the observed lifetimes in `.cache/mcp-vertex/`:
 *
 * - `drift/`, `bootstrap/` — one-shot analyses; nothing rereferences
 *   them after ~2 weeks.
 * - `verify/`, drivers (`s3-driver/`, `s4-s5-driver/`) — generated by
 *   lints that re-run on demand; a week is plenty.
 * - `rules/` — the `rules_get_rules` cache; freshness beats persistence.
 * - `state/*.jsonl` — keep the last N journal files (same convention as
 *   `logs`).
 * - `.worktrees/*` — orphan git worktrees left by crashed agents
 *   (f00072 S5); keep the most-recent N, prune the rest.
 *
 * The `maxAgeDays` cap lets a host SHORTEN (never silently lengthen) the
 * built-in `olderThanDays` lifetimes from `mcp-vertex.config.json`
 * without forking this module: each rule's effective age is
 * `min(builtin, maxAgeDays)`.
 */
import type { ICacheEvictionRule } from '@mcp-vertex/core/public';

/** Tuning surfaced from `config.cache` (f00072 S3). */
export interface IStaticRuleOptions {
	/** Upper cap (days) applied to every `olderThanDays` rule. Default 30. */
	readonly maxAgeDays?: number;
	/** Orphan-worktree sweeper tuning (f00072 S5). */
	readonly worktrees?: {
		readonly enabled?: boolean | undefined;
		readonly keepLastN?: number | undefined;
	};
}

/** Owner tag stamped on every rule this plugin contributes. */
export const CACHE_OWNER = 'cache' as const;

const DEFAULT_MAX_AGE_DAYS = 30;
const DEFAULT_WORKTREES_KEEP = 3;

/** Clamp a built-in lifetime to the host's `maxAgeDays` cap. */
const cappedDays = (builtin: number, maxAgeDays: number): number =>
	Math.min(builtin, maxAgeDays);

/**
 * Build the cache plugin's static rule set, applying the host's
 * `config.cache` tuning. Pure over its input — no I/O, no clock.
 */
export const buildStaticRules = (
	options: IStaticRuleOptions = {},
): readonly ICacheEvictionRule[] => {
	const maxAgeDays = options.maxAgeDays ?? DEFAULT_MAX_AGE_DAYS;
	const worktreesEnabled = options.worktrees?.enabled ?? true;
	const worktreesKeepLastN =
		options.worktrees?.keepLastN ?? DEFAULT_WORKTREES_KEEP;

	const olderThan = (
		id: string,
		path: string,
		builtinDays: number,
	): ICacheEvictionRule => ({
		id,
		owner: CACHE_OWNER,
		path,
		when: {
			kind: 'olderThanDays',
			days: cappedDays(builtinDays, maxAgeDays),
		},
	});

	return [
		olderThan('drift-snapshots', 'drift/*', 14),
		olderThan('bootstrap-snapshots', 'bootstrap/*', 14),
		olderThan('verify-snapshots', 'verify/*', 7),
		olderThan('s3-driver-snapshots', 's3-driver/*', 7),
		olderThan('s4-s5-driver-snapshots', 's4-s5-driver/*', 7),
		olderThan('rules-snapshots', 'rules/*', 30),
		// `keepLastN` operates on the direct children of the named
		// DIRECTORY (the registry rejects a file/glob target for this
		// strategy), so the path is the bare directory — not `state/*`.
		{
			id: 'state-journal-roll',
			owner: CACHE_OWNER,
			path: 'state',
			when: { kind: 'keepLastN', n: 5 },
		},
		// f00072 S5 — orphan worktree sweeper. Keeps the most-recent N
		// crashed-agent worktrees under `<cacheDir>/.worktrees/<agent>/`,
		// prunes the rest by mtime. Disabled via `config.cache.worktrees`.
		{
			id: 'cache-worktrees-orphans',
			owner: CACHE_OWNER,
			path: '.worktrees',
			when: { kind: 'keepLastN', n: worktreesKeepLastN },
			enabled: worktreesEnabled,
		},
	];
};
