/**
 * `discoverTutorials` — scan `plugins/<plugin>/tutorials/<lang>/*.md` and
 * return a structured catalogue the docs site can render. See l100 s7.
 *
 * Tutorial files have a YAML frontmatter:
 *
 *   ---
 *   title: Getting started
 *   plugin: proposals
 *   audience: orchestrator / agent
 *   order: 1
 *   ---
 *
 *   # body…
 *
 * `title` is REQUIRED (the catalogue indexes by it). The other fields
 * are advisory and default sensibly. Body is the markdown content
 * AFTER the closing `---` line; the docs site renders it as-is.
 *
 * The directory layout is fixed: `plugins/<plugin>/tutorials/<lang>/<slug>.md`.
 * A plugin is "tutorial-eligible" when its `tutorials/` directory
 * exists; we don't require any specific number of files (zero is
 * valid — the site just skips the Tutorial tab for that plugin).
 *
 * SRP: this module is pure (no I/O outside the injected reader), so
 * tests can run in milliseconds against an in-memory filesystem.
 */

import type { Lang } from '../../src/i18n/shared';

export interface ITutorial {
	readonly plugin: string;
	readonly lang: Lang;
	readonly slug: string;
	readonly title: string;
	readonly audience?: string;
	readonly order?: number;
	readonly body: string;
	/**
	 * True when the tutorial body was generated by the bootstrap
	 * pipeline (`scripts/translate-tutorials.sh`) and not yet reviewed.
	 * Renderers should surface a "needs review" badge; check-tutorials-i18n
	 * counts these toward the "unfinished translation" total.
	 */
	readonly autoTranslated?: boolean;
	/** True when the auto-translated body still needs a human pass. */
	readonly needsHumanReview?: boolean;
}

/** Minimal reader contract — keeps the function pure and testable. */
export interface ITutorialReader {
	readonly listDirs: (path: string) => readonly string[];
	readonly readFile: (path: string) => string | undefined;
	readonly join: (...parts: string[]) => string;
}

/** Parse YAML-ish frontmatter from a markdown file. Defensive: returns
 *  an empty record on any parse failure so the body still surfaces. */
const parseFrontmatter = (
	raw: string,
): { meta: Record<string, string>; body: string } => {
	if (!raw.startsWith('---')) return { meta: {}, body: raw };
	const end = raw.indexOf('\n---', 3);
	if (end < 0) return { meta: {}, body: raw };
	const headerBlock = raw.slice(3, end).trim();
	const body = raw.slice(end + 4).replace(/^\r?\n/, '');
	const meta: Record<string, string> = {};
	for (const line of headerBlock.split(/\r?\n/)) {
		const m = /^([a-zA-Z][\w-]*):\s*(.+)$/.exec(line.trim());
		if (m) meta[m[1] as string] = (m[2] as string).trim();
	}
	return { meta, body };
};

/** Slugify a filename: `getting-started.md` → `getting-started`. */
const slugOf = (fileName: string): string =>
	fileName.replace(/\.md$/i, '').replace(/[^a-zA-Z0-9_-]+/g, '-');

const sortByOrderThenTitle = (a: ITutorial, b: ITutorial): number => {
	const ao = a.order ?? Number.POSITIVE_INFINITY;
	const bo = b.order ?? Number.POSITIVE_INFINITY;
	if (ao !== bo) return ao - bo;
	return a.title.localeCompare(b.title);
};

/**
 * Walk `pluginsDir/<plugin>/tutorials/<lang>/<slug>.md` for every plugin
 * × language combo, parse the frontmatter, and return the flat list.
 *
 * Errors are swallowed per-file (a single broken markdown file MUST NOT
 * take down the whole site). Missing titles fall back to the slug so
 * the catalogue is never empty for an existing file.
 */
export const discoverTutorials = (
	pluginsDir: string,
	languages: readonly Lang[],
	reader: ITutorialReader,
): readonly ITutorial[] => {
	const plugins = reader.listDirs(pluginsDir);
	const out: ITutorial[] = [];
	for (const plugin of plugins) {
		const tutorialsDir = reader.join(pluginsDir, plugin, 'tutorials');
		for (const lang of languages) {
			const langDir = reader.join(tutorialsDir, lang);
			const files = reader.listDirs(langDir);
			for (const fileName of files) {
				if (!fileName.endsWith('.md')) continue;
				const path = reader.join(langDir, fileName);
				const raw = reader.readFile(path);
				if (raw === undefined) continue;
				const { meta, body } = parseFrontmatter(raw);
				out.push({
					plugin,
					lang,
					slug: slugOf(fileName),
					title: meta.title ?? slugOf(fileName),
					...(meta.audience !== undefined
						? { audience: meta.audience }
						: {}),
					...(meta.order !== undefined &&
					!Number.isNaN(Number(meta.order))
						? { order: Number(meta.order) }
						: {}),
					// l110 s3: surface the auto-translated / review flags so
					// downstream consumers (capabilities.json, Tutorial.astro)
					// can mark untranslated tutorials without re-parsing
					// frontmatter themselves.
					...(meta['auto-translated'] === 'true'
						? { autoTranslated: true }
						: {}),
					...(meta['needs-human-review'] === 'true'
						? { needsHumanReview: true }
						: {}),
					body,
				});
			}
		}
	}
	return out.sort((a, b) => {
		if (a.plugin !== b.plugin) return a.plugin.localeCompare(b.plugin);
		if (a.lang !== b.lang) return a.lang.localeCompare(b.lang);
		return sortByOrderThenTitle(a, b);
	});
};

/** Group tutorials by plugin → lang → ordered list. Convenience for
 *  the renderer so `PluginPage.astro` does not redo the bucketing. */
export const groupByPluginLang = (
	tutorials: readonly ITutorial[],
): ReadonlyMap<string, ReadonlyMap<Lang, readonly ITutorial[]>> => {
	const map = new Map<string, Map<Lang, ITutorial[]>>();
	for (const t of tutorials) {
		const pluginMap = map.get(t.plugin) ?? new Map<Lang, ITutorial[]>();
		const list = pluginMap.get(t.lang) ?? [];
		list.push(t);
		pluginMap.set(t.lang, list);
		map.set(t.plugin, pluginMap);
	}
	const out = new Map<string, ReadonlyMap<Lang, readonly ITutorial[]>>();
	for (const [plugin, pluginMap] of map.entries()) {
		out.set(plugin, pluginMap as ReadonlyMap<Lang, readonly ITutorial[]>);
	}
	return out;
};
